(fix) xtask: blocking -> async (#2050)
## Description

We missed the removal of the blocking client in `xtask` during the
[asyncification](https://github.com/apollographql/rover/pull/2035). This
PR fixes that.

```
 Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 12s
     Running `target/debug/xtask prep`
...
thread 'main' panicked at /Users/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Testing
`cargo xtask prep` does not panic.