rover_std: introduce new print macros (#2090)
## Description

Following on from the emoji deprecation, this PR intrpduces 3 new
macros: `infoln!`, `warnln!` and `errln!`.

An example of how the new macros look:
```
$ rover command 
==> This is an info message
warn: This is a warning message
error: This is an error message
```

Using the current Style enum defined
[here](https://github.com/apollographql/rover/blob/72e346c926b4ba0a09d6971d224aeefb32ad9e30/crates/rover-std/src/style.rs),
coloring of text will adhere to the user’s terminal preferences.
Similarly to current rover functionality, a user may set the `NO_COLOR`
env var to disable stlyised output.

The macros will also expand format args, similarly to how `println!` and
`eprintln!` work. The below usage will yield the same output:
```rust
let msg = "Hello, World!";
infoln!("some info message: {msg}");
infoln!("some info message: {}", msg);
```

More info can be found in the design doc:
https://apollographql.atlassian.net/wiki/spaces/Rover/pages/818020417/2024-08-20+Rover+output+UX+improvements