`rover dev` without supergraph config, prompting for subgraph url/name and creating SchemaSource::Introspection from it (#2312)
`legacy`

[nix-shell:~/apollo/retail-supergraph]$ rover dev
⚠️ Do not run this command in production! ⚠️ It is intended for local
development.
🕸️ what URL is your subgraph running on?:
http://localhost:4001/checkout/graphql
🧑 what is the name of this subgraph?: checkout
WARN: could not detect a schema in the current working directory. to
watch a schema, pas
s the '--schema <PATH>' argument
👂 polling http://localhost:4001/checkout/graphql every 1 second
🛫 starting a session with the 'checkout' subgraph
🎶 composing supergraph with Federation v2.9.3
error[E029]: Encountered 2 build errors while trying to build a
supergraph.

Caused by:
EXTERNAL_MISSING_ON_BASE: Field "Variant.price" is marked @external on
all the subgr
aphs in which it is listed (subgraph "checkout").
NO_QUERIES: No queries found in any subgraph: a supergraph must have a
query root ty
pe.
    
The subgraph schema you provided is invalid. See
https://www.apollographql.com/d
ocs/federation/errors/ for more information on resolving build errors.

^C
✋ shutting down the `rover dev` session and all attached processes...



`next`
[nix-shell:~/apollo/retail-supergraph]$ ../rover/target/debug/rover dev
what URL is your subgraph running on?:
http://localhost:4001/checkout/graphql
what is the name of this subgraph?: checkout
error: Encountered 2 build errors while trying to build a supergraph.

Caused by:
EXTERNAL_MISSING_ON_BASE: Field "Variant.price" is marked @external on
all the subgr
aphs in which it is listed (subgraph "checkout").
NO_QUERIES: No queries found in any subgraph: a supergraph must have a
query root ty
pe.