installers: add aarch64-unknown-linux-musl check (#2079)
## Description

As we do not currently release builds for `aarch64-unknown-linux-musl`,
the nix installer script will currently fail to download a binary on
this platform. This is most commonly seen when running a Linux based
Docker container on macOS.

This PR adds a check that returns early to prevent a download failure.

## Testing

Tested in a Docker container on macOS:
```
$ cat Dockerfile
FROM alpine
RUN apk add bash curl
ADD ./installers/binstall/scripts/nix/install.sh /tmp/install.sh
RUN /tmp/install.sh

$ docker build .
------
 > [4/4] RUN /tmp/install.sh:
0.086 This operating system does not support dynamic linking to glibc.
0.088 ERROR: Unsupported platform: aarch64-unknown-linux-musl
------
Dockerfile:4
--------------------
   2 |     RUN apk add bash curl
   3 |     ADD ./installers/binstall/scripts/nix/install.sh /tmp/install.sh
   4 | >>> RUN /tmp/install.sh
   5 |
--------------------
ERROR: failed to solve: process "/bin/sh -c /tmp/install.sh" did not complete successfully: exit code: 1
```