fix: detect improper VS code pastes on windows (#1268)
fixes #1026.

if you run `rover config auth` from VS Code's default PowerShell config on Windows, the API key file will always be saved with these contents:

```toml
api_key = "\u0016"
```

This is clearly incorrect! This PR adds new error messages for users who created their API keys in this way that look like this:

```console
$ rover config whoami
error[E035]: The API key associated with profile "default" is corrupt.
        Recreate this configuration profile by running `rover config auth`.
```

and if new users try to press "ctrl+v" in their integrated VS Code terminal, we will detect that case and error, instructing them on what to do instead.

```console
$ rover config auth
Go to https://studio.apollographql.com/user-settings/api-keys and create a new Personal API Key.
Copy the key and paste it into the prompt below.
>
error: Your API key was not pasted successfully.
        Re-run this command, and when you are prompted to enter your API key, right click on the terminal and press paste instead of pressing Ctrl+V.
```