[BGS-201] when `APOLLO_GRAPH_REF` is set and bad credentials are provided, user should get informative error.
was
```
~/src/fed-quickstart/retail-supergraph(main *=) ~/src/rover/target/debug/rover  dev  --graph-ref Retail-Supergraph-j5fgoc@prod --profile BAD_PROFILE
retrieving subgraphs remotely from Retail-Supergraph-j5fgoc@prod
merging supergraph schema files
error: Failed to load remote subgraphs.
Data was returned, but with errors

Caused by:
    0: Data was returned, but with errors
    1: Data was returned, but with errors
```

updated to:


```
~/src/fed-quickstart/retail-supergraph(nik/test-cases-for-manual-tests *) ~/src/rover/target/debug/rover  dev  --graph-ref Retail-Supergraph-j5fgoc@prod --profile BAD_PROFILE
retrieving subgraphs remotely from Retail-Supergraph-j5fgoc@prod
merging supergraph schema files
error: Failed to load remote subgraphs.
You don't have the required permissions to perform this operation: attempting to fetch subgraphs.

Caused by:
    You don't have the required permissions to perform this operation: attempting to fetch subgraphs.
  ```